### ISSUE TITLE
What if I want to add my Keyboard & Mouse

### ISSUE THREAD

**Issue by sachin-devitpl** [Fanman03/JackNetRGBSync#11]
Hello there, 
What if I want to add my Keyboard & Mouse ? Do I have any guide to add new Device ?

**Comment by Fanman03** [comment]
Hello.

If you would like to add support for an unsupported device you would need to write an [RGB.NET](https://github.com/darthAffe/RGB.NET)device provider. Once you have a device provider .DLL file, you can simply move it into the `DeviceProvider` directory of JackNet RGB Sync and it will see your device.
