### ISSUE TITLE
Led group lost at startup

### ISSUE THREAD

**Issue by AlejandroMataGuillen** [Fanman03/JackNetRGBSync#12]
Hi, I started using the program and it's awesome. Now I have an Asus mobo with, HyperX RGB ram and an Asus Strix GPU, also a Corsair cooler. I managed to have everything synchronized without the mobo on the master led using your video because my mobo is not showing. The only problem is when I start my pc my LEDs are not syncing I need to go every time to the JackNet app and drag the things again. Also I used your video to run the app on the startup but my led group is not saving correctly. Thanks, btw really awesome app, I wish you would help me

**Comment by Fanman03** [comment]
Hello!

Make sure you manually save the settings at least once by closing the app with the X button in the upper right corner. If you do not manually close the app, the settings are not saved.
