### ISSUE TITLE
binary for ubuntu 18.04 ? 

### ISSUE THREAD

**Issue by guillaume-larche** [Fanman03/JackNetRGBSync#5]
Hi, 

Your JackNet RGB Sync Sw seems good to me. Indeed, I bought a K70 Corsair and I would like to custom it, but under Linux. 

Could you provide your sources or could you provide a binary for ubuntu 18.04 ? 

Thanks a lot for your answer.

Regards.

**Comment by Legion2** [comment]
JackNet requires iCUE to control Corsair devices and iCUE is not available for linux, so this won't work.

**Comment by guillaume-larche** [comment]
Ok, understood. For the records, I found what I looked for : https://github.com/ckb-next/ckb-next 

Regards.
